### ISSUE TITLE
Error: Cannot find module 'path'

### ISSUE THREAD

**Issue by yazaldefilimone** [twoslashes/twoslash#5] opened 2024-01-14 18:08 UTC
```ts
import { transformerTwoSlash } from 'shikiji-twoslash';

```

![image](https://github.com/twoslashes/twoslash/assets/78354432/998138c8-6d0d-4e3e-b6ab-8a7d017e7267)

```sh
 ⨯ Error: Cannot find module 'path'
    at webpackEmptyContext (.../.next/server/app/[slug]/page.js:22:10)
    at requirePath (webpack-internal:///(rsc)/./node_modules/.pnpm/@typescript+vfs@1.5.0/node_modules/@typescript/vfs/dist/vfs.esm.js:592:132)
```

**Comment by antfu** [comment] 2024-01-14 19:11
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed by antfu** 2024-01-14 19:11 UTC

**Comment by Autsider666** [comment] 2024-08-02 16:42
For anyone running into this issue when using next.js: https://github.com/shikijs/twoslash/issues/191#issuecomment-1928681921
